### ISSUE TITLE
TOC page numbering incorrect

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/isodoc-word#2]
Currently TOC only gets updated on manual "Update Field" right click in Word, we wish the real TOC could be generated directly.

```
Foreword	i
Introduction	i
1. Scope	1
2. Normative References	1
3. Terms and Definitions	1
4. Specifications	1
4.1. General, organoleptic and health characteristics	1
4.2. Physical and chemical characteristics	1
```

**Comment by ronaldtse** [comment]
From @opoudjis:

http://sebsauvage.net/wiki/doku.php?id=word_document_generation#comment_6b3c2ba23c65ef74c211b3b914075d49

A note about computed field:
* Computed fields include TOC (table of content), page refences and so on.
* With Word, when you open a document, all computed fields are not updated by default. This has to be done manually by typing CTRL+A (to select the whole document) then press F9.

Thus, all computed fields you insert in your document will not show up unless the user manually updates them. This a problem related to Word itself. There is not simple solution to this.
As you can't predict the page numbers, the TOC needs to be manually updated by the user (Not a heavy burden, and I guess it's possible to automate this by including a script in the file. I'll investigate that later.)

... Script in file: maybe VBA, but I'm nervous about doing things like that. And again, ISO already want you to hit F9 in their template.

**Comment by opoudjis** [comment]
I can probably populate the entries of the TOC manually, as long as word does not inject too much ad hoc code. But there is no way I can automatically generate page numbers. It might be possible to include a VBA script to update the table of contents on opening the document.

**Comment by ronaldtse** [comment]
That would already be much better. Page numbers definitely would differ on the paper size defined, so that would be out of our scope (unless we directly render to PDF, which will need a correct TOC)

**Comment by opoudjis** [comment]
Duplicates https://github.com/riboseinc/isodoc/issues/4 , moving there.
